FROM node:alpine as build
WORKDIR /app
COPY package.json .
RUN npm install
RUN mkdir node_modules/.vite && chmod -R 777 node_modules/.vite
COPY . .
RUN npm run build

FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80