version: '3.8'
services:
  client:
    build: .
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        target: /app/node_modules